[versions]
agp = "8.12.0"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activity = "1.10.1"
androidx-lifecycle = "2.8.0"
composeMultiplatform = "1.8.1"
kotlin = "2.1.21"
kotlinStdlib = "2.1.21"
lensLogger = "1.0.0"
ktorVersion = "3.0.1"
napierVersion = "2.6.1"
jbNavigation = "2.9.0-alpha14"
vanniktech = "0.32.0"
composeHotReload = "1.0.0-alpha11"
kotlinx-coroutines = "1.10.2"
datastoreVersion = "1.1.7"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
androidx-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jbNavigation" }

ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-client-serializer = { module = "io.ktor:ktor-client-serialization", version.ref = "ktorVersion" }
ktor-json-serializer = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-client-android-engine = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorVersion" }
ktor-client-cio-engine = { module = "io.ktor:ktor-client-cio", version.ref = "ktorVersion" }
ktor-client-ios-engine = { module = "io.ktor:ktor-client-ios", version.ref = "ktorVersion" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorVersion" }
lens-module = { module = "io.github.farhazulmullick:lens-logger", version.ref = "lensLogger" }
napier = { module = "io.github.aakira:napier", version.ref = "napierVersion" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
datastore-core = { module = "androidx.datastore:datastore", version.ref = "datastoreVersion" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastoreVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }